# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_topo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='us_lab_topology_data',
            name='content',
            field=models.TextField(default={}),
            preserve_default=False,
        ),
    ]
