# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_topo', '0002_us_lab_topology_data_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='us_lab_settings_data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=50)),
                ('value', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='us_lab_topology_data',
            name='id',
        ),
        migrations.AlterField(
            model_name='us_lab_topology_data',
            name='name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
