# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_topo', '0007_auto_20170417_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='us_lab_settings_data',
            name='id',
        ),
        migrations.AlterField(
            model_name='us_lab_settings_data',
            name='key',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
