# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_topo', '0008_auto_20170418_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='us_lab_resource_plan_data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('minIp', models.GenericIPAddressField()),
                ('maxIp', models.GenericIPAddressField()),
                ('ip_prefix', models.IntegerField()),
                ('gateway', models.GenericIPAddressField()),
                ('minHaId', models.IntegerField()),
                ('maxHaId', models.IntegerField()),
                ('minVlan', models.IntegerField()),
                ('maxVlan', models.IntegerField()),
                ('minOspfId', models.IntegerField()),
                ('maxOspfId', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
