# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_topo', '0010_auto_20170419_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='us_lab_resource_plan_data',
            name='ip_prefix',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
