# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_topo', '0012_auto_20170419_0604'),
    ]

    operations = [
        migrations.CreateModel(
            name='us_lab_resource_plan_ha_id',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('minHaId', models.IntegerField(blank=True, null=True)),
                ('maxHaId', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='us_lab_resource_plan_ip_address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('minIp', models.GenericIPAddressField(blank=True, null=True)),
                ('maxIp', models.GenericIPAddressField(blank=True, null=True)),
                ('ip_prefix', models.IntegerField(blank=True, null=True)),
                ('gateway', models.GenericIPAddressField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='us_lab_resource_plan_ospf_id',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('minOspfId', models.IntegerField(blank=True, null=True)),
                ('maxOspfId', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='us_lab_resource_plan_vlan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('minVlan', models.IntegerField(blank=True, null=True)),
                ('maxVlan', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
